### ISSUE TITLE
Auto-commits size management

### ISSUE THREAD

**Issue by pratapvardhan** [github/covid19-dashboard#103]
Currently the repo size (raw) is around ~1GB? Should we consider options to reduce incremental rewrites of notebooks? Or perhaps reduce autocommit frequency (if at all, for some notebooks)?

Absolutely a low priority item at the moment.

**Comment by hamelsmu** [comment]
wow good point.  I wonder if I should wipe out commit history and start all over again, or I should wipe out commit history each time.  Not sure -- one part I'm worried about is that it will also wipe out the contributors as well

**Comment by hamelsmu** [comment]
I wonder if 

- `git clone --depth 1` 
- `git pull --depth 1`

will help in this situation.  Thoughts?

**Comment by pratapvardhan** [comment]
Clearly I'm not expert on history pruning. If our objective is to reduce size, does squashing consecutive autoupdate commits from history and force rebase push help (not sure)?

And,  https://github.com/CSSEGISandData/COVID-19 seems to be updating data once a day now? Should 3/6/12 hour update be okay now, instead of hourly?

**Comment by hamelsmu** [comment]
You are right.  I changed it to update every 12 hours.

**Comment by hamelsmu** [comment]
> Clearly I'm not expert on history pruning. If our objective is to reduce size, does squashing consecutive autoupdate commits from history and force rebase push help (not sure)?

This is a good idea, I'm no expert in Git either, despite where I work :p  I think being reduced by an order of magnitude now that we are going from 24 to 2 times a day will help.  If things get bad I can just wipe out all commit history forcefully

**Comment by hamelsmu** [comment]
Ok I guess I can close this issue now.  Thanks for raising it.
