### ISSUE TITLE
Updates failing due case-count-estimation-us-states

### ISSUE THREAD

**Issue by pratapvardhan** [github/covid19-dashboard#128]
Update job [failed](https://github.com/github/covid19-dashboard/runs/527347548?check_suite_focus=true#step:10:93) -- probably an endpoint issue?

I've 2 questions
- Can we skip failing notebooks (try, skip?) instead of not updating other valid notebooks?
- Can we manually trigger an update?

**Comment by hamelsmu** [comment]
Yeah I'll fix this today

**Comment by jwrichar** [comment]
No idea why this is failing.  I'm able to run it locally.

Perhaps they're blocking some API requests?

**Comment by hamelsmu** [comment]
I tried running this manually inside a GitHub Actions container, and the data was retrieved successfully, so perhaps the API for 'https://covidtracking.com/api/states/daily' is flaky hard to tell because I cannot reproduce

**Comment by hamelsmu** [comment]
Closing this issue, new workflow that fails gracefully and runs all other notebooks if there is an error.  https://github.com/github/covid19-dashboard/runs/528545009?check_suite_focus=true

**Comment by pratapvardhan** [comment]
@hamelsmu -- ton of work there! 🙏
