### ISSUE TITLE
Upcoming Changes In John Hopkins Dataset

### ISSUE THREAD

**Issue by hamelsmu** [github/covid19-dashboard#159]
Looks like some of the changes could be breaking changes

See:  https://github.com/CSSEGISandData/COVID-19/issues/1250#issue-585788363

The procedure for handling this is any failing dashboards will be hidden from view from the home page if notebooks happen to fail.  Just want to give everyone a heads up

@twiecki @jwrichar @jbduarte @pratapvardhan @aimran-adroll @avyfain

**Comment by pratapvardhan** [comment]
@hamelsmu -- major bummer would be, they would be dropping recovered cases, we might need to drop showing that number..

**Comment by hamelsmu** [comment]
Yeah looks like they are dropping it because they aren’t confident in that number

**Comment by westmich** [comment]
Any word on confirmed/death cases by state?  That seems to have stopped coming through.

**Comment by avyfain** [comment]
@westmich I have been using the API from https://covidtracking.com/ for that purpose.

**Comment by hamelsmu** [comment]
@aimran-adroll I had to deprecate your chart because the data is no longer available for John Hopkins and has been archived.  I have temporarily moved your chart into the `_drafts/` folder.  

I have attempted my best to rescue as many of the other charts as possible.

**Comment by hamelsmu** [comment]
# The following dashboards have been temporarily deprecated and moved into `_/drafts` for failures due to changes in data

@jwrichar Your dashboard `Estimating The Mortality Rate For COVID-19¶` is now in the drafts folder
@aimran-adroll as previously mentioend your state dashboard is now in drafts
@pratapvardhan all three overview notebooks are in drafts (I thought I had fixed problems but there are still some )
@adrianturcato your dashboard is also breaking due to changes in the underlying data you are pulling from. 

Sorry folks, I figure its best to temporarily move these off the home page rather than show erroneous data or stale data.  Let me know if you have any thoughts / comments

**Comment by twiecki** [comment]
@hamelsmu Noticed that mine wasn't mentioned here, does it still work?

**Comment by hamelsmu** [comment]
@twiecki , yeah your stuff still works without issues, I was able to make some fixes easily to point to the new data file.  You don't have any issues b/c you are not using any US-State level data, only country level

**Comment by rysarmstr** [comment]
@hamelsmu / @pratapvardhan  looks like the link the the "US" pane of the "Covid-19 Overview" page is still not working... giving a 404. Thank you all for the great dashboards!

**Comment by adrianturcato** [comment]
@hamelsmu Thanks and no problem! I have been working on getting that sorted out, hopefully will have it done tomorrow.

**Comment by hamelsmu** [comment]
@rysarmstr We are aware of that issue and the page was intentionally deprecated, I added a blank page with a warning instead, now. Thanks for reporting it!

**Comment by hamelsmu** [comment]
Closing this issue -- everyone except @jwrichar's dashboard has been, which I have deprecated until its fixed.  Thanks everyone for assisting in this!
