### ISSUE TITLE
Add CLI Projects?

### ISSUE THREAD

**Issue by ahmadawais** [github/covid19-dashboard#162]
Thanks a lot for creating this. I am trying to help make the #COVID19 data more accessible to everyone. I [tweeted the CLI I wrote](https://twitter.com/MrAhmadAwais/status/1240719414229716992) to help track that myself. Since then the community has come around helped and improved this project by a lot. 

There are thousands of people consuming these stats resulting in millions of hits daily on the API. I was wondering it mentioning this project would be a good way to improve covid-190-dashboard a11y.

Here's the GitHub repo → [https://github.com/ahmadawais/corona-cli](https://github.com/ahmadawais/corona-cli)

**Comment by hamelsmu** [comment]
Please add your project to the related page  - instructions are on that page https://covid19dashboards.com/related/
