### ISSUE TITLE
add "doubling in 2 days, doubling in 4 days" lines to covid19-dashboard/_notebooks/2020-03-17-compare-trajectories.ipynb

### ISSUE THREAD

**Issue by henfri** [github/covid19-dashboard#226]
Hello,

thanks for these great graphs. 
I would find it useful to have lines for doubling of cases withing 2 and 4 days added to the graph (in addition to the 33% daily growth)

Greetings,
Hendrik

**Comment by hamelsmu** [comment]
Thanks I’m not sure we are in a position to take on feature requests, only bugs at this time, but feel free to make a PR and we will review it!

Closing this for now
