### ISSUE TITLE
Regarding site's mobile-friendliness

### ISSUE THREAD

**Issue by paras-jain** [github/covid19-dashboard#228]
Although fastpages sites are mobile-friendly, some of the plots are large in size.
![photo_2020-03-29_13-45-37](https://user-images.githubusercontent.com/57864667/77844349-c4a60f00-71c3-11ea-8a5b-78ea19abc25d.jpg)
![photo_2020-03-29_13-45-43](https://user-images.githubusercontent.com/57864667/77844351-c5d73c00-71c3-11ea-9ebd-cf999f9b9ffe.jpg)

**Comment by hamelsmu** [comment]
I have no idea how to fix this, if anyone else has any ideas I could use help with this!

**Comment by paras-jain** [comment]
Note: Apparently, the issue seems to be with interactive plots only.

I tried configuring plot dimensions with no luck, so any help with this will be appreciated.

**Comment by christophrrb** [comment]
Do you know where the configuration is for Vega for this webpage? I see it when I inspect the element on the website, but I don't know where to find it in the code.

**Comment by hamelsmu** [comment]
It’s generated with Altair automatically

**Comment by iamashks** [comment]
I will give it a look. I'm working on design template of overview pages (https://github.com/github/covid19-dashboard/pull/250), and I checked the Jekyll theme too. I will try to make all more mobile-friendly.

**Comment by paras-jain** [comment]
@iamashks I don't think tweaking the [fastpages](https://github.com/fastai/fastpages) jekyll theme will be any help because it is already optimized for mobile viewing. As [mentioned](https://github.com/github/covid19-dashboard/issues/228#issuecomment-605647025) [above](https://github.com/github/covid19-dashboard/issues/228#issuecomment-605757401), I think you might try configuring Vega for Altair generated plots.

**Comment by iamashks** [comment]
@paras-jain Thanks for your suggestion. I was only mentioning my current work above. I will be checking Vega for Altair as it's mentioned by you and Christopher above. :)

**Comment by shubhampandeyhld** [comment]
I think you should declare .marks class as flex-direction:column for mobile devices so that it easily fits on small screens .In current scenario its is good at big screens .. laptops but not at mobile screens because your wrapper class is being collapsed  with .marks class .So .you need too move marks class inside wrapper class for small devices using css flex-box

**Comment by hamelsmu** [comment]
@shubhampandeyhld  can you share a concrete example with a working prototype?

**Comment by pratapvardhan** [comment]
I'm not so sure, what should the mobile friendly version. Should 

- The chart width be resized to device width? Then it might make the chart small and unreadable
- Or keep the size as is, but wrap the container with a scrollbar?

**Comment by paras-jain** [comment]
@pratapvardhan wrapping in a container didn't occur to my mind, it would definitely be better than resizing the Altair plot.

**Comment by shubhampandeyhld** [comment]
Sorry ,I need some time right now  I  having some pending work .I will join
you guys very soon.

**Comment by imran2712** [comment]
Busy day need to end soon dear

**Comment by hellmoney888** [comment]
get well soon readmore[ball-reallife.com](url)

**Comment by thanggy** [comment]
<a href="https://c.jumia.io/?a=110616&c=1423&p=r&E=kkYNyk2M4sk%3D&utm_campaign=110616&utm_term="><img src="https://affiliates.jumia.com/banners/Jumia Nigeria/Deals-of-the-day/250x250.jpg"/></a>

**Comment by imran2712** [comment]
Mistake

**Comment by shubhampandeyhld** [comment]
Sorry ,for being late .
So ,what we want is something like this:
![mobile jpg](https://user-images.githubusercontent.com/51791904/79338627-46789500-7f45-11ea-9d5f-9fc0d435f141.png)
