### ISSUE TITLE
FT-style chart for fatalities

### ISSUE THREAD

**Issue by laventura** [github/covid19-dashboard#239]
Hi @hamelsmu - I've created an FT-style chart for fatality curves for countries. 

Sample is here: https://github.com/laventura/covid19/blob/master/Covid19_Fatality_Curves_FT_style.ipynb

Would that be of interest for the dashboard? I'd love to contribute.

Thank you! 🙏🏻

**Comment by hamelsmu** [comment]
Looks really nice.  Perhaps this is a good opportunity to merge this into @pratapvardhan 's dashboards....

Thoughts?

**Comment by hamelsmu** [comment]
@laventura Can you add this additional chart ?  https://twitter.com/jburnmurdoch/status/1245106818344538126?s=21

**Comment by laventura** [comment]
@hamelsmu Ah yes, I saw that late last night. Would love to do it. Let me check it out.

**Comment by hamelsmu** [comment]
@laventura great when you are ready I think we will add these charts as a separate dashboard as is.

**Comment by pratapvardhan** [comment]
@laventura -- that'd be great, please tag me when you need any help with review or anything to move in the direction.

**Comment by laventura** [comment]
@pratapvardhan  Thanks. Am working on it. Will share something this afternoon.

**Comment by hamelsmu** [comment]
@laventura I'm closing this issue, please open a PR whenever you are ready!  Thanks
