### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by jszym** [github/covid19-dashboard#241]
It seems covid19dashboard.com is down.

Sends 301 and redirects to 185.199.111.153.
https://isitup.org/check.php?domain=covid19dashboards.com

and that ip is down
https://isitup.org/check.php?domain=185.199.111.153

**Comment by hamelsmu** [comment]
it works for me ... are you still getting this?

**Comment by hamelsmu** [comment]
I believe this is resolved.  Feel free to reopen
