### ISSUE TITLE
Per Capita cases of COVID-19 cases by state is visually tricky

### ISSUE THREAD

**Issue by dansbecker** [github/covid19-dashboard#242]
I'm going to state my suggestion through an example:

Many people looking at the following graph will conclude that CO has had faster per-capita  growth than CA, because it's higher on the vertical axis for any given horizontal value.

![image](https://user-images.githubusercontent.com/1390442/78201319-8e2ff480-744e-11ea-9de5-d2fe897c253a.png)

But the two lines are approximately parallel, indicating the same level of growth. So why is CO on a higher line? It's an artifact of population size. By using an inclusion criterion based on absolute cases (having 100 cases), the vertical value at Day 0 is a function of population size.

It's a contrast to the graph above it, which uses population size as both the vertical axis and the selection criteria

![image](https://user-images.githubusercontent.com/1390442/78201545-1c0bdf80-744f-11ea-8c37-6474b91dd0b3.png)

There each state starts at the same vertical value on day 0 (the origin). In that graph, vertical height at any given x-value is indeed an accurate measure of growth in the quantity being depicted.

I'd suggest doing the same thing for the per-capita graph. Every state has surprised 50 cases per million of population. That could be a good candidate for inclusion in the graph

![image](https://user-images.githubusercontent.com/1390442/78201724-950b3700-744f-11ea-91f2-e8b3462e856b.png)

**Comment by hamelsmu** [comment]
I agree with this, thanks for pointing this out

**Comment by hamelsmu** [comment]
Fixed this in https://github.com/github/covid19-dashboard/commit/20856b85542f1e1b0d26f67a552566cac864265a

Changes

![image](https://user-images.githubusercontent.com/1483922/78277104-cb38cd00-74c8-11ea-83c0-30990c8182d0.png)


![image](https://user-images.githubusercontent.com/1483922/78277086-c4aa5580-74c8-11ea-8df8-ded35cbb4782.png)
