### ISSUE TITLE
Duplicate Country names in Data

### ISSUE THREAD

**Issue by jimypbr** [github/covid19-dashboard#260]
From looking at the 'COVID-19 Growth Rate Prediction' dashboard I see there are multiple entries in the dataset for the same countries. For example there is: 'United Kingdom' and 'United Kingdom (total)'. The first one appears to be the correct one, while the second one has different much smaller numbers. Is this a bug or does it have a different meaning in the dataset (e.g. deaths)? 

In the plot for growth rates in 'COVID-19 Growth Rate Prediction' the wrong 'United Kingdom' entry is used.

Thank you, and excellent job on this project!

**Comment by hamelsmu** [comment]
this has been fixed
