### ISSUE TITLE
Growth-By-State graph titles don't update, so they become wrong

### ISSUE THREAD

**Issue by dansbecker** [github/covid19-dashboard#272]
The tables show titles `Compare Something  for the US with CA, WA, NY`. But they show this title even when CA, WA and NY aren't shown (e.g. because the user selected something else). It'd be better to either update the titles to reflect what is in the graph, or just use a more generic title like **Case Counts over time for US States**

![image](https://user-images.githubusercontent.com/1390442/78511524-8926ba00-775a-11ea-87c2-b60a5c684189.png)

**Comment by hamelsmu** [comment]
Good call, I made the change you suggested in https://github.com/github/covid19-dashboard/commit/2879bc4d58952c466f5be8a9bd41c6a874d8b24c

Thanks for keeping an eye out
