### ISSUE TITLE
[Help Needed] Alone in my project 

### ISSUE THREAD

**Issue by Thomas423-admin** [github/covid19-dashboard#299]
I am developing a social networking app , but one for people who are needing someone there for them to help , in today's world kids are hiding all their feelings, all their pain from their family , friends , and they think no one understands them. All they need is someone who understands ,someone to talk to and get it off their chest but it's good for everyone during the COD (19). It will give everyone someone to talk to ft/video chat , voice call, chat ... Plz I'm relatively new to this but I have a Idea , I Have the motivation, and the Want. Can I get a few people to help join me.

**Comment by Kali-Jim** [comment]
emm……
Ok

**Comment by Thomas423-admin** [comment]
> emm……
> Ok

Would you help??

**Comment by Kali-Jim** [comment]
What can I do for you?

**Comment by AboAllam** [comment]
how can i help you

**Comment by ManirajBollapragada** [comment]
I too am ready to contribute. let me know the start point.

**Comment by imran2712** [comment]
K

**Comment by LuisFlavioOliveira** [comment]
Alright, it could be quite useful. But honestly,  I don't like the idea of kids talking with strangers on a social network without supervision.

**Comment by thanggy** [comment]
<a href="https://c.jumia.io/?a=110616&c=1423&p=r&E=kkYNyk2M4sk%3D&utm_campaign=110616&utm_term="><img src="https://affiliates.jumia.com/banners/Jumia Nigeria/Deals-of-the-day/250x250.jpg"/></a>

**Comment by Thomas423-admin** [comment]
> What can I do for you?

Well I'm looking for a good program to use but can't find one that would make my program run smooth with little crashes .

**Comment by Thomas423-admin** [comment]
> how can i help you

Well I need a little help with figuring out the code configuration atm.

**Comment by Thomas423-admin** [comment]
> I too am ready to contribute. let me know the start point.

Well I'm trying to get the start point to fully co-operate with a program without crashing so much

**Comment by dmitryilyuk** [comment]
Выражаю готовность внести свой вклад в проект

**Comment by thanggy** [comment]
<a href="
https://c.jumia.io/?a=110616&c=1423&p=r&E=kkYNyk2M4sk%3D&utm_campaign=110616&utm_term="><img
src="https://affiliates.jumia.com/banners/Jumia
Nigeria/Deals-of-the-day/250x250.jpg"/></a>

**Comment by hamelsmu** [comment]
@github/platform-health this repo has started to get lots of spam from various actors for example this issue and other PRs 

cc: @T-Holland
