### ISSUE TITLE
Looking for data about Age

### ISSUE THREAD

**Issue by arungupta21** [github/covid19-dashboard#320]
Hi Collaborators,

I am working on a visualization concept, for which I require the data about **Age** of the people died and/or infection. 
This may be at any level granularity.

If you know the source of such dataset, please let me know. Your hep will be highly appreciated.

Thanks and regards
Arun

**Comment by hamelsmu** [comment]
Closing this issue b/c it is stale, doesn't appear to be any activity ... you could try the "Covid19"  category on the fastai forums https://forums.fast.ai/c/covid-19/52
