### ISSUE TITLE
Dashboard vs. VPS

### ISSUE THREAD

**Issue by WMoscow** [github/covid19-dashboard#329]
Hello, friends.

I really liked your Dashboard! I’ve been trying to install it for a week on VPS running Ubuntu and on my macbook, but 139 ruby ​​error constantly appears.

Here is the detailed error: https://sun9-43.userapi.com/c855532/v855532056/2288f2/MSa6xmAwvZo.jpg

What could be the problem?

**Comment by hamelsmu** [comment]
I am not sure, I have not designed or documented this project in such a way to allow other people to host these dashboards outside GitHub pages.  Also I am not sure what that error is.  

I would suggest starting with [fastpages](https://github.com/fastai/fastpages) and read that README carefully to understand how this website works.
