### ISSUE TITLE
Suggestion to reduce .git folder size, sync times, and commit noise

### ISSUE THREAD

**Issue by artdgn** [github/covid19-dashboard#332]
Currently all notebooks and all images are committed every deployment (every 6 hours). 
This has some big advantages: 
- Reproducibility.
- Simplicity. 
- NB viewer for PRs. 

This his also many disadvantages: 
- `.git` folder data is getting very large (900GB).
- Sync times are getting slow. 
- Notebook files changes are hard to review (not diff-friendly).
- NB-viewer is not really a reliable way to render the notebooks (with all the various JS and HTML used in them),
- Bot commits are adding lots of noise to the commit history.
- Changes need to always be rebased on top of bot commits even if no actual changes besides deployment happened.

Fortunately, there is a tool that makes life with Jupyter notebooks and git much easier (at least for me): https://github.com/mwouts/jupytext. It is an incredibly comfortable way of working in both an IDE and a notebook simultaneously, but most importantly it makes git life much easier:
- Notebook files are "paired" to `.py` files (with some comments to store structure and markdown) and are synced together locally.
- `.py` are committed to git, whereas `.ipynb` files are not (e.g. ignored in `.gitignore`).
- During deployments [a command](https://github.com/artdgn/pages/blob/0bf4ebf6b8db19342be74741baf014386f2795a0/_action_files/run_notebooks.sh#L13) to generate `.ipynb` is used (they will contain only inputs, and no outputs), and than papermill can run them to fill them with up to date outputs. Nothing needs to be committed, because `.py` files haven't changed.
- For local development Jupyter will automatically open the `.py` files with the metadata as notebooks when jupytext is installed. Otherwise a [short Makefile target](https://github.com/artdgn/pages/blob/0bf4ebf6b8db19342be74741baf014386f2795a0/Makefile#L78) can create / update all notebooks using the same script that's used during deployment.

In my own [repo](https://github.com/artdgn/pages) (where I work on the various visualisations / calculations) I've switched to this system and am very happy about it:
- Only meaningful commits are in the history and there is no tradeoff between deployment schedule and git noise (although I keep it to once a day, since there is no hurry). 
- I can clearly see changes I'm committing using the diff on the `.py` files. 
- The changes are all very light weight since they don't contain data and random JSON noise.

With COVID-19 not likely to be over quickly any time soon it might be a good idea to give this a chance. It's pretty simple, and can be gradual (notebooks can be moved to this system and git-removed gradually).

**Comment by hamelsmu** [comment]
ipynb files must be committed to github in order to trigger the page build.  I don't see way around that.  I agree there is tons of data in the git history

I would suggest doing only a shallow clone of the repo

`git fetch --depth 1`

`git clone --depth 1  <repo URL>`

**Comment by hamelsmu** [comment]
Is there anything else you can suggest that would clean up the git history in the repo?  I could wipe all commits but I feel that is poor manners as that would erase everyone from the GitHistory... 

I guess I could clean it and sign it as a bot so that at least it doesn't appear as if though I made all the commits?

**Comment by artdgn** [comment]
@hamelsmu 

> ipynb files must be committed to github in order to trigger the page build. I don't see way around that. 

Not sure what you mean by that. The page build is executed on schedule / push (in this case it would be a change to `.py` file that is committed and pushed, and during the udpate-action it is converted to a notebook and than run by papermill and deployed). 

> Is there anything else you can suggest that would clean up the git history in the repo? I could wipe all commits but I feel that is poor manners as that would erase everyone from the GitHistory...

I think that there several steps:
1. Stopping committing updates to notebooks / images during deployment will stop adding noise (by stopping bot commits). After that, history should start growing mush more slowly, commit history will be clean from both commits and rebasing will be needed less frequently. The changes to action files and scripts are fairly minimal for this. 
2. Cleaning up all previous bot commits from history can further reduce size (although I'm not sure how to do that exactly in git).
3. After moving to using `.py` files - the corresponding `.ipynb` files can be removed from history (by `git filter-branch`). The rewritten empty commits (because of removed `.ipynb` files) can be left to keep contribution history intact.

I think step 1 is the most significant in reducing noise, and 2 and 3 are for reducing size. After this process my repo (not the fork of this one, the [other](https://github.com/artdgn/pages) one) went from around 200 MB to 15 MB, no commits are added by deployments, and I can be sure of any changes because of meaningful and short diffs.

**Comment by hamelsmu** [comment]
Wow this is the coolest visualization I have ever seen, BTW really impressed @artdgn I didn't know this was possible with python

**Comment by artdgn** [comment]
> Wow this is the coolest visualization I have ever seen, BTW really impressed @artdgn I didn't know this was possible with python

I'm guessing you refer to the world-map I've added to the notebook? Thanks! Hope this is not sarcasm :)

**Comment by hamelsmu** [comment]
No it’s not sarcasm I genuinely have learned something new today

Thanks for sharing and contributing

**Comment by hamelsmu** [comment]
@artdgn ok trying to understand your comments (apologies if I am slow):

> Stopping committing updates to notebooks / images during deployment will stop adding noise (by stopping bot commits)

Wow when I think about this carefully I guess you are right!  Why am I committing the notebooks It is totally not necessary!  At least the automated refresh has no need to be committed.  I will try this and as you mentioned this will alleviate the conflicts!

> For local development Jupyter will automatically open the .py files with the metadata as notebooks when jupytext is installed. Otherwise a short Makefile target can create / update all notebooks using the same script that's used during deployment.

I am trying to wrap my head around this a bit more.  The fastpages machinery converts Jupiter notebooks directly to HTML.  I suppose to avoid notebooks completely we would have to do a round trip back to Jupyter before converting to HTML within the automated process.  Is this what you mean?

Thanks again for your thoughtful suggestions!

**Comment by artdgn** [comment]
> Thanks again 

My pleasure. And thanks for adding triage permissions.

>  I suppose to avoid notebooks completely we would have to do a round trip back to Jupyter before converting to HTML within the automated process. Is this what you mean?

It might help to think of `.ipynb` as binary files (compiled artifacts) of the source `.py` files.
So  `**/*.ipynb` is in `.gitignore` (so that new files aren't comited implicitely).

So there are two scenarios:
- Deployment (in update-notebook action):
   - Everything happens as today, but `run_notebooks.sh` [has an extra step before papermill](https://github.com/artdgn/pages/blob/master/_action_files/run_notebooks.sh#L11) that uses jupytext to create the `.ipynb` files which are than calculated by papermill. For the `.py` files the extra step means: jupytext(`.py`) > papermill(`.ipynb`) > Jekyll(`.ipynb`) > Jekyll(`.md`) > `.html`. For the existing `.ipynb` files that aren't part of this system everything happens as before.
- Local: 
   - If working within virtual environment that has `jupytext` (made by `make install` e.g.) you just open `.py` file - it opens as notebook (it creates the notebook and opens it). You run it and edit it. When you save the notebook, it automagically updates the the `.py` file.
   - Jekyll local server makes the posts out of the `.ipynb` files that exist locally (but aren't git comited). So changes can be checked in Jekyll. If not working in jupyter at all (but making changes to `.py` files or just viewing) `make notebooks` will run `run_notebooks.sh` locally to create the `.ipynb` files for Jekyll.
   - If not working within virtual environment someone (why?) the person will either need to install jupytext along with all the rest of the dependencies or use Makefile targets (like `mane notebook` and `make save-notebooks`) to manually sync `.py` and `.ipynb` files.

**Comment by hamelsmu** [comment]
I made the changes to deployment, I am not sure I have time for jupytext etc but can try that in the future.  

Closing this issue for now, but feel free to keep discussing

**Comment by artdgn** [comment]
@hamelsmu perhaps the other relatively simple size reduction step to look into is removing the bot update commits from the history to make the repo smaller. Not sure how this will affect existing forks though.

**Comment by hamelsmu** [comment]
Yeah not sure how to do that in a clean way .... I'll keep thinking about this

**Comment by nehalecky** [comment]
Dropping in here after this issue was closed, but also searching for workflows to allow for [Jupytext](https://github.com/mwouts/jupytext) use with [fastpages](https://github.com/fastai/fastpages), for the reasons similar to those discussed here. They're both such powerful tools for notebook management and publishing. There's not too much else I could find on the web!

> It might help to think of .ipynb as binary files (compiled artifacts) of the source .py files.
So **/*.ipynb is in .gitignore (so that new files aren't comited implicitely).
@artdgn, agree, and this is a useful analogy, thank you. I look forward to this perspective to help evolve the serialization format for Jupyter notebooks. Hopefully soon!

@hamelsmu, if you ever do consider a workflow to leverage use of Jupytext for fastpages, would be great if you could mention this issue so I can be notified! 😄 

Also, FWIW, a reference to discussions on how to use execute a notebook created with Jupytext (including use of Papermill) https://github.com/mwouts/jupytext/issues/231 

Thanks!
