### ISSUE TITLE
[Feature request]API

### ISSUE THREAD

**Issue by dustindog101** [github/covid19-dashboard#405]
it would be nice if you guys could add an api Specifically GET to get total countries etc

**Comment by hamelsmu** [comment]
Thanks, not going to offer an API

**Comment by dustindog101** [comment]
why not

**Comment by dustindog101** [comment]
why not

**Comment by hamelsmu** [comment]
This dashboard is a community contributed set of Jupiter notebooks that render as dashboards.  The data is outside of our control and come from various places.  I would suggest following the notebooks and contacting the data providers and ask them for an API (however you might be able to make your own API as many of these data are stored in GitHub Repos, so you don't really need an API).  If you inspect the notebooks behind each dashboard you can see where the data comes from.
