### ISSUE TITLE
Metadata Update

### ISSUE THREAD

**Issue by reeshmabijosh** [github/covid19-dashboard#484]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data https://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/JYZBIG
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by hamelsmu** [comment]
This site doesn't contain a dataset, it is only a collection of code that pulls from other datasets
