### ISSUE TITLE
Canada variants of concern dashboard should use Greek labels instead of country names

### ISSUE THREAD

**Issue by anomal** [github/covid19-dashboard#643]
https://github.com/github/covid19-dashboard/blob/master/_notebooks/2021-04-03-canada-variants-of-concern.ipynb should use the [World Health Organization (WHO)'s Greek labels](https://www.who.int/en/activities/tracking-SARS-CoV-2-variants/) "Alpha", "Beta", "Gamma" instead of "UK", "South Africa", "Brazil", respectively.

**Comment by anomal** [comment]
@KamalSinghKhanna Do you want to work on this?

**Comment by KamalSinghKhanna** [comment]
yes

**Comment by anomal** [comment]
Fixed by https://github.com/github/covid19-dashboard/pull/705
