### ISSUE TITLE
another issue

### ISSUE THREAD

**Issue by kassouna** [github/covid19-dashboard#68]
thank you for the last resolved issue 

and now another one 

File "/content/load_covid_data.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

Sincerely

**Comment by hamelsmu** [comment]
Where is this happening?  What notebook?

**Comment by kassouna** [comment]
colab:
https://colab.research.google.com/github/machine-learning-apps/covid19-dashboard/blob/master/_notebooks/2020-03-16-covid19_growth_bayes.ipynb

**Comment by hamelsmu** [comment]
Thanks this has been fixed
