### ISSUE TITLE
COVID-19 Deaths Per Capita - problem with display

### ISSUE THREAD

**Issue by delsuc** [github/covid19-dashboard#85]
This graph is very useful, thanks
However the graph and the table do not show the same value.
I Believe the table is in log_10 while the graph is in Log_e  - log_10 would be much better.

**Comment by hamelsmu** [comment]
@delsuc Thanks for reporting this!  This has been fixed now!  Please feel to reopen if this is not the case

**Comment by delsuc** [comment]
Thanks, looks good to me !
