### ISSUE TITLE
COVID-19 Deaths Per Capita: Inconsistent logarithm bases

### ISSUE THREAD

**Issue by mwbinger** [github/covid19-dashboard#90]
The "Doubles every X days" lines are in log2, whereas the plotted data is uses natural logarithm.

**Comment by hamelsmu** [comment]
I'm going to remove these lines for now.  @jbduarte do you want to give a shot at fixing this?  

P.S. 
I think any real doubling in x days would appear as a curved line, not a straight diagonal line?

**Comment by mwbinger** [comment]
The doubling lines remain straight lines, but have a different slope. With y-axis as the natural log of the number of cases or deaths, the correct slope for these is just ln(2)/(doubling time in days), where ln is the natural log.

**Comment by hamelsmu** [comment]
Oh you’re right because the x axis is still in the normal scale 

I guess I can make this change easily I’ll go ahead and do this

**Comment by hamelsmu** [comment]
Actually, I'll let @jbduarte fix this as I don't want to mess something up unintentionally

**Comment by hamelsmu** [comment]
@jbduarte just fixed this via https://github.com/github/covid19-dashboard/commit/b10d09c23d3ffbcbe1b75fedcef16e67dc9a6f56
